version: "3.8"
services:
  backend:
    build:
      context: ./flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
